### ISSUE TITLE
Issue with shrine of ruin

### ISSUE THREAD

**Issue by ZeetLex** [0-Sandman/Sandswept#12]
Used shrine of ruin on stage 4. Entered simulacrum on stage 5, Cleared the stage and stage boss. Used the teleporter and ended up in another simulacrum stage without enemies, portal and/or obective. Looked around for a good 15min but could not find anything. Fell trough the floor somewhere and i have now been falling for 5 minutes. 

Seams like there is a issue somewhere, or a feature that i did not understand ? :)

**Comment by Jack-RParker** [comment]
This just happened to me as well, using version 1.1.1

**Comment by hifoomin** [comment]
this is another issue technically, should be fixed in the next patch
