### ISSUE TITLE
Universal VIP Pass Bugged

### ISSUE THREAD

**Issue by BellaRoka** [0-Sandman/Sandswept#2]
Universal VIP Pass doesn't seem to be functioning at all. Ran a test on a clean build with nothing but Sandswept, [Aerolt](https://thunderstore.io/package/Lodington/Aerolt/) (for testing), and the necessary dependencies installed and no amount of spent gold was given back to me on next stage start.

**Comment by hifoomin** [comment]
Thanks for the report, this will be fixed in the upcoming update
