### ISSUE TITLE
Sun Fragment Unlock Bug?

### ISSUE THREAD

**Issue by BellaRoka** [0-Sandman/Sandswept#3]
May or may not be a bug, but I've killed literally (and I mean literally, I'm not being hyperbolic I swear) every enemy type in the game with Sandswept installed and the unlock hasn't ever triggered. Maybe I'm just dumb though and don't understand how the unlock is supposed to work.

**Comment by hifoomin** [comment]
the unlock is scrapping a planula :^) we will reword it next update for sure

**Comment by BellaRoka** [comment]
Ah gotcha, I had a feeling I was just misinterpreting something. Thanks for the info!
