### ISSUE TITLE
Nuclear Salvo consistently breaks after being taken from Mithrix

### ISSUE THREAD

**Issue by Pumamori** [0-Sandman/Sandswept#4]
Good day,

I've been trying to do a few runs with engineer for various challenges, but I've noticed that everytime I complete the Mithrix encounter with this item specifically, the fire rate goes completely crazy, shooting thousands of nuclear missiles in short succession, leading to hefty lag & potential crashes. 

Just figured I'd mention it as it happened twice now - I didn't think to grab a log but I'll try to next time if needed.

**Comment by Smxrez** [comment]
Thanks for the report we are aware of it, and it will hopefully be fixed in the next update.

**Comment by hifoomin** [comment]
fixed in the upcoming version
