### ISSUE TITLE
Motivator Elites spam console with "Team Buff" while existing.

### ISSUE THREAD

**Issue by Coffe-e** [0-Sandman/Sandswept#7]
Title pretty much says it all. I'm gonna do more testing to see if its just a mod conflict or not, but I doubt a mod conflict would cause this.

**Comment by hifoomin** [comment]
Can't reproduce - no logging in the mod either - most likely another mod

**Comment by hifoomin** [comment]
If you could send your mod list with a mod profile where this issue occurs, that would be greatly appreciated
mod manager > settings > search for dependency or dependencies, and there should be a list of your mods that you can copy

**Comment by prodzpod** [comment]
its vanillavoid

**Comment by Coffe-e** [comment]
Firstly, i'd like to apologize for not getting the logs/modlist to you guys sooner, I ended up busy and spaced that I had sent this. Thank you for the help even in spite of this though, its very appreciated!
