### ISSUE TITLE
Game doesn't launch correctly after 1.0 update

### ISSUE THREAD

**Issue by DamageMaximo** [0-Sandman/Sandswept#9]
I even disabled all mods and only enabled Sandswept and it's dependecies, and when the game is loading, and it reaches 99% this appears in the console and then it stays there

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.Items.ContagiousItemManager.InitTransformationTable () (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_004C)
(wrapper dynamic-method) RoR2.Items.ContagiousItemManager.DMD<RoR2.Items.ContagiousItemManager::Init>()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.Items.ContagiousItemManager::Init>?1905016114()
Sandswept.Items.VoidGreens.FesteringHunger.ContagiousItemManager_Init (On.RoR2.Items.ContagiousItemManager+orig_Init orig) (at C:/Users/User/Desktop/Development/RoR2/Sandswept/Sandswept/Items/VoidGreens/FesteringHunger.cs:136)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.Items.ContagiousItemManager::Init>?1380619080()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.Items.ContagiousItemManager::Init>?582314862()
Sandswept.Items.VoidGreens.Millenium.ContagiousItemManager_Init (On.RoR2.Items.ContagiousItemManager+orig_Init orig) (at C:/Users/User/Desktop/Development/RoR2/Sandswept/Sandswept/Items/VoidGreens/Millenium.cs:230)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.Items.ContagiousItemManager::Init>?1764793744()
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <7e05db41a20b45108859fa03b97088d4>:IL_006A)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <7e05db41a20b45108859fa03b97088d4>:IL_0083)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <7e05db41a20b45108859fa03b97088d4>:IL_0000)
RoR2BepInExPack.VanillaFixes.FixSystemInitializer+<LogBadCycle>d__3.MoveNext () (at <aa1f8befe6b949ad816e156bda547267>:IL_022A)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0026)

**Comment by hifoomin** [comment]
Do you have smouldering document disabled?

**Comment by DamageMaximo** [comment]
Yeah

**Comment by hifoomin** [comment]
Yeah, this behavior should be fixed in the next patch
